//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace Remoting.ADCCheckUser {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IGPSM2MDataServerSoap", Namespace="http://adc.siinterface.com/")]
    public partial class IGPSM2MDataServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ADCCheckUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ADCSIInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrdOrdNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginVerifyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IGPSM2MDataServer() {
            this.Url = global::Remoting.Properties.Settings.Default.Remoting_ADCCheckUser_IGPSM2MDataServer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ADCCheckUserCompletedEventHandler ADCCheckUserCompleted;
        
        /// <remarks/>
        public event ADCSIInterfaceCompletedEventHandler ADCSIInterfaceCompleted;
        
        /// <remarks/>
        public event CheckUserCompletedEventHandler CheckUserCompleted;
        
        /// <remarks/>
        public event GetPrdOrdNumCompletedEventHandler GetPrdOrdNumCompleted;
        
        /// <remarks/>
        public event LoginVerifyCompletedEventHandler LoginVerifyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adc.siinterface.com/ADCCheckUser", RequestNamespace="http://adc.siinterface.com/", ResponseNamespace="http://adc.siinterface.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GpsResponse ADCCheckUser(string sECCode, string sUserId, string sUserPwd, string sVerifyCode) {
            object[] results = this.Invoke("ADCCheckUser", new object[] {
                        sECCode,
                        sUserId,
                        sUserPwd,
                        sVerifyCode});
            return ((GpsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ADCCheckUserAsync(string sECCode, string sUserId, string sUserPwd, string sVerifyCode) {
            this.ADCCheckUserAsync(sECCode, sUserId, sUserPwd, sVerifyCode, null);
        }
        
        /// <remarks/>
        public void ADCCheckUserAsync(string sECCode, string sUserId, string sUserPwd, string sVerifyCode, object userState) {
            if ((this.ADCCheckUserOperationCompleted == null)) {
                this.ADCCheckUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnADCCheckUserOperationCompleted);
            }
            this.InvokeAsync("ADCCheckUser", new object[] {
                        sECCode,
                        sUserId,
                        sUserPwd,
                        sVerifyCode}, this.ADCCheckUserOperationCompleted, userState);
        }
        
        private void OnADCCheckUserOperationCompleted(object arg) {
            if ((this.ADCCheckUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ADCCheckUserCompleted(this, new ADCCheckUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adc.siinterface.com/ADCSIInterface", RequestNamespace="http://adc.siinterface.com/", ResponseNamespace="http://adc.siinterface.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdcSiResponse ADCSIInterface(AdcSiRequest request) {
            object[] results = this.Invoke("ADCSIInterface", new object[] {
                        request});
            return ((AdcSiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ADCSIInterfaceAsync(AdcSiRequest request) {
            this.ADCSIInterfaceAsync(request, null);
        }
        
        /// <remarks/>
        public void ADCSIInterfaceAsync(AdcSiRequest request, object userState) {
            if ((this.ADCSIInterfaceOperationCompleted == null)) {
                this.ADCSIInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnADCSIInterfaceOperationCompleted);
            }
            this.InvokeAsync("ADCSIInterface", new object[] {
                        request}, this.ADCSIInterfaceOperationCompleted, userState);
        }
        
        private void OnADCSIInterfaceOperationCompleted(object arg) {
            if ((this.ADCSIInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ADCSIInterfaceCompleted(this, new ADCSIInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adc.siinterface.com/CheckUser", RequestNamespace="http://adc.siinterface.com/", ResponseNamespace="http://adc.siinterface.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckUser(string sECCode, string sUserId, string sUserPw, bool bAllowPhoneLogin) {
            object[] results = this.Invoke("CheckUser", new object[] {
                        sECCode,
                        sUserId,
                        sUserPw,
                        bAllowPhoneLogin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserAsync(string sECCode, string sUserId, string sUserPw, bool bAllowPhoneLogin) {
            this.CheckUserAsync(sECCode, sUserId, sUserPw, bAllowPhoneLogin, null);
        }
        
        /// <remarks/>
        public void CheckUserAsync(string sECCode, string sUserId, string sUserPw, bool bAllowPhoneLogin, object userState) {
            if ((this.CheckUserOperationCompleted == null)) {
                this.CheckUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserOperationCompleted);
            }
            this.InvokeAsync("CheckUser", new object[] {
                        sECCode,
                        sUserId,
                        sUserPw,
                        bAllowPhoneLogin}, this.CheckUserOperationCompleted, userState);
        }
        
        private void OnCheckUserOperationCompleted(object arg) {
            if ((this.CheckUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adc.siinterface.com/GetPrdOrdNum", RequestNamespace="http://adc.siinterface.com/", ResponseNamespace="http://adc.siinterface.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPrdOrdNum(string tel) {
            object[] results = this.Invoke("GetPrdOrdNum", new object[] {
                        tel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrdOrdNumAsync(string tel) {
            this.GetPrdOrdNumAsync(tel, null);
        }
        
        /// <remarks/>
        public void GetPrdOrdNumAsync(string tel, object userState) {
            if ((this.GetPrdOrdNumOperationCompleted == null)) {
                this.GetPrdOrdNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrdOrdNumOperationCompleted);
            }
            this.InvokeAsync("GetPrdOrdNum", new object[] {
                        tel}, this.GetPrdOrdNumOperationCompleted, userState);
        }
        
        private void OnGetPrdOrdNumOperationCompleted(object arg) {
            if ((this.GetPrdOrdNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrdOrdNumCompleted(this, new GetPrdOrdNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adc.siinterface.com/LoginVerify", RequestNamespace="http://adc.siinterface.com/", ResponseNamespace="http://adc.siinterface.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GpsResponse LoginVerify(string sECCode, string sUserId, string sUserPw) {
            object[] results = this.Invoke("LoginVerify", new object[] {
                        sECCode,
                        sUserId,
                        sUserPw});
            return ((GpsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LoginVerifyAsync(string sECCode, string sUserId, string sUserPw) {
            this.LoginVerifyAsync(sECCode, sUserId, sUserPw, null);
        }
        
        /// <remarks/>
        public void LoginVerifyAsync(string sECCode, string sUserId, string sUserPw, object userState) {
            if ((this.LoginVerifyOperationCompleted == null)) {
                this.LoginVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginVerifyOperationCompleted);
            }
            this.InvokeAsync("LoginVerify", new object[] {
                        sECCode,
                        sUserId,
                        sUserPw}, this.LoginVerifyOperationCompleted, userState);
        }
        
        private void OnLoginVerifyOperationCompleted(object arg) {
            if ((this.LoginVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginVerifyCompleted(this, new LoginVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adc.siinterface.com/")]
    public partial class GpsResponse {
        
        private int resultCodeField;
        
        private string resultMsgField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adc.siinterface.com/")]
    public partial class AdcSiResponse {
        
        private int actionCodeField;
        
        private string bizCodeField;
        
        private int dealkindField;
        
        private int priorityField;
        
        private string resultCodeField;
        
        private string resultMsgField;
        
        private string sIAppIDField;
        
        private string svcContField;
        
        private int testFlagField;
        
        private string timeStampField;
        
        private string transIDField;
        
        private string versionField;
        
        /// <remarks/>
        public int ActionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BizCode {
            get {
                return this.bizCodeField;
            }
            set {
                this.bizCodeField = value;
            }
        }
        
        /// <remarks/>
        public int Dealkind {
            get {
                return this.dealkindField;
            }
            set {
                this.dealkindField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
            }
        }
        
        /// <remarks/>
        public string SIAppID {
            get {
                return this.sIAppIDField;
            }
            set {
                this.sIAppIDField = value;
            }
        }
        
        /// <remarks/>
        public string SvcCont {
            get {
                return this.svcContField;
            }
            set {
                this.svcContField = value;
            }
        }
        
        /// <remarks/>
        public int TestFlag {
            get {
                return this.testFlagField;
            }
            set {
                this.testFlagField = value;
            }
        }
        
        /// <remarks/>
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public string TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adc.siinterface.com/")]
    public partial class AdcSiRequest {
        
        private int actionCodeField;
        
        private string bizCodeField;
        
        private int dealkindField;
        
        private int priorityField;
        
        private string sIAppIDField;
        
        private string svcContField;
        
        private int testFlagField;
        
        private string timeStampField;
        
        private string transIDField;
        
        private string versionField;
        
        /// <remarks/>
        public int ActionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BizCode {
            get {
                return this.bizCodeField;
            }
            set {
                this.bizCodeField = value;
            }
        }
        
        /// <remarks/>
        public int Dealkind {
            get {
                return this.dealkindField;
            }
            set {
                this.dealkindField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string SIAppID {
            get {
                return this.sIAppIDField;
            }
            set {
                this.sIAppIDField = value;
            }
        }
        
        /// <remarks/>
        public string SvcCont {
            get {
                return this.svcContField;
            }
            set {
                this.svcContField = value;
            }
        }
        
        /// <remarks/>
        public int TestFlag {
            get {
                return this.testFlagField;
            }
            set {
                this.testFlagField = value;
            }
        }
        
        /// <remarks/>
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public string TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ADCCheckUserCompletedEventHandler(object sender, ADCCheckUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ADCCheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ADCCheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GpsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GpsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ADCSIInterfaceCompletedEventHandler(object sender, ADCSIInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ADCSIInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ADCSIInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdcSiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdcSiResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckUserCompletedEventHandler(object sender, CheckUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPrdOrdNumCompletedEventHandler(object sender, GetPrdOrdNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrdOrdNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrdOrdNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoginVerifyCompletedEventHandler(object sender, LoginVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GpsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GpsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591